const countryIds = [
    {
        "id":"CN",
        "country":"China"
    }
    ,{
        "id":"IT",
        "country":"Italy"
    }
    ,{
        "id":"US",
        "country":"USA"
    }
    ,{
        "id":"IR",
        "country":"Iran"
    }
    ,{
        "id":"KR",
        "country":"S-Korea"
    }
    ,{
        "id":"GB",
        "country":"UK"
    }
    ,{
        "id":"CZ",
        "country":"Czechia"
    }
    ,{
        "id":"SA",
        "country":"Saudi-Arabia"
    }
    ,{
        "id":"RU",
        "country":"Russia"
    }
    ,{
        "id":"HK",
        "country":"Hong-Kong"
    }
    ,{
        "id":"ZA",
        "country":"South-Africa"
    }
    ,{
        "id":"SM",
        "country":"San-Marino"
    }
    ,{
        "id":"TW",
        "country":"Taiwan"
    }
    ,{
        "id":"AE",
        "country":"UAE"
    }
    ,{
        "id":"CR",
        "country":"Costa-Rica"
    }
    ,{
        "id":"DO",
        "country":"Dominican-Republic"
    }
    ,{
        "id":"CZ",
        "country":"Czechia"
    }
    ,{
        "id":"VN",
        "country":"Vietnam"
    }
    ,{
        "id":"BA",
        "country":"Bosnia-and-Herzegovina"
    }
    ,{
        "id":"FO",
        "country":"Faeroe-Islands"
    }
    ,{
        "id":"MK",
        "country":"North-Macedonia"
    }
    ,{
        "id":"LK",
        "country":"Sri-Lanka"
    }
    ,{
        "id":"BF",
        "country":"Burkina-Faso"
    }
    ,{
        "id":"NZ",
        "country":"New-Zealand"
    }
    ,{
        "id":"TT",
        "country":"Trinidad-and-Tobago"
    }
    ,{
        "id":"RE",
        "country":"R&eacute;union"
    }
    ,{
        "id":"CD",
        "country":"DRC"
    }
    ,{
        "id":"PR",
        "country":"Puerto-Rico"
    }
    ,{
        "id":"GF",
        "country":"French-Guiana"
    }
    ,{
        "id":"PF",
        "country":"French-Polynesia"
    }
    ,{
        "id":"CI",
        "country":"Ivory-Coast"
    }
    ,{
        "id":"GQ",
        "country":"Equatorial-Guinea"
    }
    ,{
        "id":"TZ",
        "country":"Tanzania"
    }
    ,{
        "id":"VI",
        "country":"US-Virgin-Islands"
    }
    ,{
        "id":"MF",
        "country":"Saint-Martin"
    }
    ,{
        "id":"NC",
        "country":"New-Caledonia"
    }
    ,{
        "id":"KY",
        "country":"Cayman-Islands"
    }
    ,{
        "id":"CW",
        "country":"Cura&ccedil;ao"
    }
    ,{
        "id":"CV",
        "country":"Cabo-Verde"
    }
    ,{
        "id":"CF",
        "country":"CAR"
    }
    ,{
        "id":"SV",
        "country":"El-Salvador"
    }
    ,{
        "id":"BL",
        "country":"St-Barth"
    }
    ,{
        "id":"IM",
        "country":"Isle-of-Man"
    }
    ,{
        "id":"LC",
        "country":"Saint-Lucia"
    }
    ,{
        "id":"AG",
        "country":"Antigua-and-Barbuda"
    }
    ,{
        "id":"VA",
        "country":"Vatican-City"
    }
    ,{
        "id":"PG",
        "country":"Papua-New-Guinea"
    }
    ,{
        "id":"VC",
        "country":"St-Vincent-Grenadines"
    }
    ,{
        "id":"SX",
        "country":"Sint-Maarten"
    }
    ,{
        "id":"SZ",
        "country":"Eswatini"
    }
    ,{
        "id":"TC",
        "country":"Turks-and-Caicos"
    }
    ,{
        "id":"VG",
        "country":"British-Virgin-Islands"
    }
    ,{
        "id":"KN",
        "country":"Saint-Kitts-and-Nevis"
    }
    ,{
        "id":"SL",
        "country":"Sierra-Leone"
    }
    ,{
        "id":"NL",
        "country":"Caribbean-Netherlands"
    }
    ,{
        "id":"FK",
        "country":"Falkland-Islands"
    }
    ,{
        "id":"EH",
        "country":"Western-Sahara"
    }
    ,{
        "id":"SS",
        "country":"South-Sudan"
    }
    ,{
        "id":"PM",
        "country":"Saint-Pierre-Miquelon"
    }
    ,{
        "id":"ST",
        "country":"Sao-Tome-and-Principe"
    }
    ,{
        "id":"SB",
        "country":"Solomon-Islands"
    }
    ,{
        "id":"WF",
        "country":"Wallis-and-Futuna"
    }
]                  
